# Generated by Django 4.2.4 on 2023-08-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=300, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('BS', 'Basic'), ('AD', 'Admin')], default='BS', max_length=2)),
                ('tg_id', models.PositiveIntegerField(blank=True, default=0, verbose_name='ID пользователя в телеграм')),
                ('user_photo', models.ImageField(blank=True, upload_to='tgbot/images/', verbose_name='Фото')),
                ('full_name', models.CharField(blank=True, max_length=300, verbose_name='ФИО сотрудника')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Должность сотрудника')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('phone_number_work', models.CharField(blank=True, max_length=20, verbose_name='Рабочий номер телефона')),
                ('email_address', models.CharField(blank=True, max_length=200, verbose_name='e-mail')),
                ('nick_name', models.CharField(blank=True, max_length=200, verbose_name='Никнейм в телеграм')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('user_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgbot.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
